# Generated by Django 3.0.8 on 2020-07-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sold_out', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Play',
                'verbose_name_plural': 'Plays',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=88)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Performance')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Play'),
        ),
        migrations.AddField(
            model_name='performance',
            name='staged_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Venue'),
        ),
    ]
